

# import sys
# getSeq = open(sys.argv[1]).read().rstrip()

seq = "GATTTGGCCATAAAGTGACAGGAGAGGTAAGGTTCTCTAGGATTAAAGAATAACGTATTCTTATTTGATTCACTTTAAAAAATTATTCTAAAATCTGTTACATATCTGTCCTCTCCAGGATGAACTTTATATTGGCTCAGCAGATTGTTTACTGTGTTCTTCTTCTTTTTCTTTTTTTGGTCTTTCCTGCTCAGCGCCCAACCCAAGTTCAAAGGCTGATAAGAGAGAAAATCTCATGAGGAGGTTTTAGTCTAGGGAAAGTCATTCAGTGGATGTGATCTTGGCTCACAGGGGACGATGTCAAGCTCTTCCTGGCTCCTTCTCAGCCTTGTTGCTGTAACTGCTGCTCAGTCCACCATTGAGGAACAGGCCAAGACATTTTTGGACAAGTTTAACCACGAAGCCGAAGACCTGTTCTATCAAAGTTCACTTGCTTCTTGGAATTATAACACCAATATTACTGAAGAGAATGTCCAAAACATGGTGAGTTCTCATGGCT"

seqDic = {}
seqList = list(seq)
seqNum = len(seqList)
for i in 'ACGT':
  for j in 'ACGT':
    seqDic[i+j] = 0

for i in range(len(seqList)-1):
  seqDic[seqList[i]+(seqList[i+1])] += 1

_width = 0
for i in seqDic:
  _seqWidth = len(str(seqDic[i]))
  if _seqWidth >=_width:
    _width = _seqWidth

seqKeyList = []
for i in seqDic:
  seqKeyList.append(i)
seqKeyList.sort()

for i in seqKeyList:
  print('{0}\t{1:0>{2}}\t{3:.2f}\t'.format(i, seqDic[i], _width, seqDic[i]/seqNum))
